RAFD-2563: Kafka read in Data Prep service unable to read from kerberised Kafka
ThalesGroup/cdap pull request #223
Opened 2019-11-22 11:46 UTC by avantika-karwasara

2019-11-25 07:13 UTC, anujkanojia requested changes

2019-11-25 07:13 UTC, anujkanojia commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +    let keyValArr = this.state.kafkaProducerProperties.pairs;
add null check for kafkaProducerProperties

2019-11-25 07:13 UTC, anujkanojia commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +        'pairs': [{
Create a constant default state for kafkaProducerProperties

2019-11-25 07:13 UTC, anujkanojia commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +      return [{
use that default value for kafkaProducerProperties

2019-11-25 07:13 UTC, anujkanojia commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +        const isSomeErrInArr = this.state.inputs[key].reduce((a,b) => { return a.concat(b);  })
Instead of a,b give logical name and assign initial value in reduce function (it might fail as a is undefined in first run)

2019-11-26 04:43 UTC, avantika-karwasara commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +    let keyValArr = this.state.kafkaProducerProperties.pairs;
done

2019-11-26 04:43 UTC, avantika-karwasara commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +        'pairs': [{
done

2019-11-26 04:43 UTC, avantika-karwasara commented on cdap-ui/app/cdap/components/DataPrepConnections/KafkaConnection/index.js
> +      return [{
done

2019-11-26 07:02 UTC, anujkanojia approved these changes
lgtm

2019-11-26 12:32 UTC, anujkanojia approved these changes
can go ahead

2019-11-26 17:07 UTC, merged